name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'yarn'

#       - name: Get yarn cache
#         id: yarn-cache
#         run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"
#
#       - name: Cache dependencies
#         uses: actions/cache@v3
#         with:
#           path: ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-

#       - name: Install Yarn
#         run: corepack prepare yarn@4.6.0 --activate

#       - name: Activate Yarn
#         run: yarn set version 4.6.0

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: ./dist
          depth: 5

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write
      pages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./dist

#       - name: Deploy
#         run: yarn deploy
#         env:
#           GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gary-dickenson.github.io
