name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Output NODE_ENV
        shell: bash
        run: |
          echo "NODE_ENV: $NODE_ENV"

      - name: Build
        run: yarn build

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          path: ./dist
          depth: 5

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write
      pages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
